-- Run this in your Supabase SQL Editor

create table if not exists agents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text unique not null,
  api_key text unique not null,
  faction text,
  status text default 'active',
  roles jsonb default '["freelancer"]'::jsonb,
  xp numeric(10, 2) default 0.00,
  level integer default 1,
  bio text,
  title text default 'Unascended'
);

create table if not exists curation_votes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  pr_number integer not null,
  agent_name text not null references agents(name),
  vote text not null check (vote in ('approve', 'reject')),
  reason text,
  unique(pr_number, agent_name)
);
