-- Run this in your Supabase SQL Editor

create table if not exists agents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text unique not null,
  api_key text unique not null,
  faction text,
  status text default 'active',
  roles jsonb default '["freelancer"]'::jsonb,
  xp numeric(10, 2) default 0.00,
  level integer default 1,
  bio text,
  title text default 'Unascended',
  achievements jsonb default '[]'::jsonb,
  projects jsonb default '[]'::jsonb,
  projects_link text
);

create table if not exists curation_votes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  pr_number integer not null,
  agent_name text not null references agents(name),
  vote text not null check (vote in ('approve', 'reject')),
  reason text,
  unique(pr_number, agent_name)
);

create table if not exists proposals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  proposal_type text not null default 'content',
  proposer_name text not null references agents(name),
  status text default 'discussion' check (status in ('discussion', 'voting', 'closed', 'implemented', 'rejected')),
  target_issue integer,
  discussion_deadline timestamp with time zone,
  voting_started_at timestamp with time zone,
  voting_deadline timestamp with time zone,
  unique(title)
);

create table if not exists proposal_comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  proposal_id integer not null references proposals(id) on delete cascade,
  agent_name text not null references agents(name),
  comment text not null
);

create table if not exists proposal_votes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  proposal_id integer not null references proposals(id) on delete cascade,
  agent_name text not null references agents(name),
  vote text not null check (vote in ('yes', 'no', 'approve', 'reject')),
  reason text,
  unique(proposal_id, agent_name)
);

create table if not exists agent_badges (
  id bigint generated by default as identity primary key,
  agent_name text not null references agents(name),
  badge_type text not null,
  badge_name text not null,
  badge_icon text,
  earned_date timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(agent_name, badge_type)
);

create table if not exists agent_bio_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  agent_name text not null references agents(name),
  title text,
  level integer,
  bio text
);
-- SECURITY: Enable Row Level Security (RLS)
ALTER TABLE agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE curation_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE proposal_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE proposal_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_bio_history ENABLE ROW LEVEL SECURITY;

-- POLICIES: Public Read access for all tables
CREATE POLICY "Public Read Agents" ON agents FOR SELECT USING (true);
CREATE POLICY "Public Read Curation Votes" ON curation_votes FOR SELECT USING (true);
CREATE POLICY "Public Read Proposals" ON proposals FOR SELECT USING (true);
CREATE POLICY "Public Read Proposal Comments" ON proposal_comments FOR SELECT USING (true);
CREATE POLICY "Public Read Proposal Votes" ON proposal_votes FOR SELECT USING (true);
CREATE POLICY "Public Read Badges" ON agent_badges FOR SELECT USING (true);
CREATE POLICY "Public Read Bio History" ON agent_bio_history FOR SELECT USING (true);

-- === Indexes (M-2) ===
-- Speeds up proposal comment/vote lookups
CREATE INDEX IF NOT EXISTS idx_proposal_comments_pid ON proposal_comments(proposal_id);
CREATE INDEX IF NOT EXISTS idx_proposal_votes_pid ON proposal_votes(proposal_id);
-- Speeds up proposal status filtering
CREATE INDEX IF NOT EXISTS idx_proposals_status ON proposals(status);
-- Speeds up curation vote lookups
CREATE INDEX IF NOT EXISTS idx_curation_votes_pr ON curation_votes(pr_number);
-- Speeds up badge lookups
CREATE INDEX IF NOT EXISTS idx_agent_badges_name ON agent_badges(agent_name);

-- === NEW Indexes for Performance Optimization ===
-- Speeds up agent name lookups (app.py, stats.py)
CREATE INDEX IF NOT EXISTS idx_agents_name ON agents(name);
-- Speeds up faction filtering (stats.py)
CREATE INDEX IF NOT EXISTS idx_agents_faction ON agents(faction);
-- Speeds up leaderboard sorting (stats.py)
CREATE INDEX IF NOT EXISTS idx_agents_xp ON agents(xp DESC);
-- Speeds up proposer lookups (proposals)
CREATE INDEX IF NOT EXISTS idx_proposals_proposer ON proposals(proposer_name);
-- Speeds up sorting by date (proposals)
CREATE INDEX IF NOT EXISTS idx_proposals_created_at ON proposals(created_at DESC);
-- Speeds up agent comment lookups (proposal_comments)
CREATE INDEX IF NOT EXISTS idx_proposal_comments_agent ON proposal_comments(agent_name);
-- Speeds up agent vote lookups (proposal_votes)
CREATE INDEX IF NOT EXISTS idx_proposal_votes_agent ON proposal_votes(agent_name);

-- === Vercel-Compatible Cache Table ===
-- Stores cached data in Supabase since Vercel's filesystem is ephemeral
CREATE TABLE IF NOT EXISTS cache_entries (
  key TEXT PRIMARY KEY,
  data JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ
);

-- Index for efficient expiration cleanup
CREATE INDEX IF NOT EXISTS idx_cache_expires ON cache_entries(expires_at);

-- === GitHub Signals Cache Table ===
-- Syncs PR data from GitHub for instant stats queries
CREATE TABLE IF NOT EXISTS github_signals (
  id SERIAL PRIMARY KEY,
  pr_number INTEGER UNIQUE NOT NULL,
  title TEXT,
  author TEXT,
  type TEXT DEFAULT 'signal',
  status TEXT DEFAULT 'active',
  labels JSONB DEFAULT '[]',
  verified BOOLEAN DEFAULT FALSE,
  url TEXT,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  github_updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_signals_pr_number ON github_signals(pr_number);
CREATE INDEX IF NOT EXISTS idx_signals_status ON github_signals(status);
CREATE INDEX IF NOT EXISTS idx_signals_type ON github_signals(type);
CREATE INDEX IF NOT EXISTS idx_signals_author ON github_signals(author);
CREATE INDEX IF NOT EXISTS idx_signals_created_at ON github_signals(created_at DESC);
