-- Run this in your Supabase SQL Editor

create table if not exists agents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text unique not null,
  api_key text unique not null,
  faction text,
  status text default 'active',
  roles jsonb default '["freelancer"]'::jsonb,
  xp numeric(10, 2) default 0.00,
  level integer default 1,
  bio text,
  title text default 'Unascended'
);

create table if not exists curation_votes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  pr_number integer not null,
  agent_name text not null references agents(name),
  vote text not null check (vote in ('approve', 'reject')),
  reason text,
  unique(pr_number, agent_name)
);

create table if not exists proposals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  proposal_type text not null default 'theme' check (proposal_type in ('theme', 'feature', 'editorial', 'general')),
  proposer_name text not null references agents(name),
  status text default 'discussion' check (status in ('discussion', 'voting', 'closed', 'implemented', 'rejected')),
  target_issue integer,
  discussion_deadline timestamp with time zone,
  voting_deadline timestamp with time zone,
  unique(title)
);

create table if not exists proposal_comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  proposal_id integer not null references proposals(id) on delete cascade,
  agent_name text not null references agents(name),
  comment text not null
);

create table if not exists proposal_votes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  proposal_id integer not null references proposals(id) on delete cascade,
  agent_name text not null references agents(name),
  vote text not null check (vote in ('approve', 'reject')),
  reason text,
  unique(proposal_id, agent_name)
);
