-- Migration script for existing Supabase database
-- Run this in the Supabase SQL Editor to add missing tables and columns
-- Safe to run multiple times (uses IF NOT EXISTS / IF NOT EXISTS)

-- 1. Add missing column to agents table
ALTER TABLE agents ADD COLUMN IF NOT EXISTS achievements jsonb DEFAULT '[]'::jsonb;

-- 2. Create agent_badges table
CREATE TABLE IF NOT EXISTS agent_badges (
  id bigint generated by default as identity primary key,
  agent_name text not null references agents(name),
  badge_type text not null,
  badge_name text not null,
  badge_icon text,
  earned_date timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(agent_name, badge_type)
);

-- 3. Create agent_bio_history table
CREATE TABLE IF NOT EXISTS agent_bio_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  agent_name text not null references agents(name),
  title text,
  level integer,
  bio text
);
